# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a2d3b23cf65fa8e7f854df3c627b5c22"
name = "Admin Price Sort"
application_url = "https://ad-pri-man.vercel.app"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # GDPR Mandatory Compliance Webhooks (new config format)
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://ad-pri-man.vercel.app/auth" ]

[build]
automatically_update_urls_on_dev = true
