# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a2d3b23cf65fa8e7f854df3c627b5c22"
name = "Admin Price Sort"
application_url = "https://ad-pri-man.vercel.app"
embedded = true

[app_info]
app_icon = "https://cdn.shopify.com/s/files/1/0234/5678/files/app-icon.png"
contact_email = "info@webtorn.com"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "https://ad-pri-man.vercel.app/webhooks/customers/data-request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "https://ad-pri-man.vercel.app/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "https://ad-pri-man.vercel.app/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://ad-pri-man.vercel.app/auth" ]
